"""add rate and desc

Revision ID: 16318f1d6ec6
Revises: be3d7a62a6d5
Create Date: 2023-10-30 21:45:07.811083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16318f1d6ec6'
down_revision: Union[str, None] = 'be3d7a62a6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_amenity_desc', table_name='amenity')
    op.add_column('apartment', sa.Column('rate', sa.Integer(), nullable=False))
    op.add_column('tag', sa.Column('desc', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'desc')
    op.drop_column('apartment', 'rate')
    op.create_index('ix_amenity_desc', 'amenity', ['desc'], unique=False)
    # ### end Alembic commands ###
