"""change a way store images apartment

Revision ID: 3534408050a0
Revises: 16318f1d6ec6
Create Date: 2023-11-12 01:56:03.177733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3534408050a0'
down_revision: Union[str, None] = '16318f1d6ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('apartment', sa.Column('total_people', sa.Integer(), nullable=False))
    op.drop_index('ix_apartment_room', table_name='apartment')
    op.drop_column('apartment', 'room')
    op.drop_column('apartment', 'img_room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('img_room', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('apartment', sa.Column('room', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_apartment_room', 'apartment', ['room'], unique=False)
    op.drop_column('apartment', 'total_people')
    op.drop_table('apartment_image')
    # ### end Alembic commands ###
