"""add status for contract

Revision ID: 597201d659dc
Revises: cf606252e069
Create Date: 2023-12-01 17:57:15.110567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597201d659dc'
down_revision: Union[str, None] = 'cf606252e069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('status', sa.String(length=42), nullable=True))
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_column('contract', 'status')
    # ### end Alembic commands ###
