"""change desc type from string255 to TEXT

Revision ID: 6ca7a5677acf
Revises: b890fa5f01e0
Create Date: 2023-11-25 22:01:57.847437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca7a5677acf'
down_revision: Union[str, None] = 'b890fa5f01e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'desc',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('apartment_comment', 'text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment_comment', 'text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('apartment', 'desc',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
