"""Add amenity table

Revision ID: 82700bb19e8b
Revises: 4444eae69fc6
Create Date: 2023-10-30 20:22:32.289082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82700bb19e8b'
down_revision: Union[str, None] = '4444eae69fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=42), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenity_name'), 'amenity', ['name'], unique=False)
    op.create_table('apartment_amenity',
    sa.Column('apartment_id', sa.String(length=255), nullable=True),
    sa.Column('amenity_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], )
    )
    op.add_column('apartment', sa.Column('price_per_day', sa.Integer(), nullable=False))
    op.add_column('apartment', sa.Column('num_bedrooms', sa.Integer(), nullable=False))
    op.add_column('apartment', sa.Column('num_living_rooms', sa.Integer(), nullable=False))
    op.add_column('apartment', sa.Column('num_bathrooms', sa.Integer(), nullable=False))
    op.add_column('apartment', sa.Column('num_toilets', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'num_toilets')
    op.drop_column('apartment', 'num_bathrooms')
    op.drop_column('apartment', 'num_living_rooms')
    op.drop_column('apartment', 'num_bedrooms')
    op.drop_column('apartment', 'price_per_day')
    op.drop_table('apartment_amenity')
    op.drop_index(op.f('ix_amenity_name'), table_name='amenity')
    op.drop_table('amenity')
    # ### end Alembic commands ###
