"""add unique for room apartment

Revision ID: 83eafcf34b8c
Revises: 9ae29a3b2d33
Create Date: 2023-10-03 15:52:21.438426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83eafcf34b8c'
down_revision: Union[str, None] = '9ae29a3b2d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apartment_room', table_name='apartment')
    op.create_index(op.f('ix_apartment_room'), 'apartment', ['room'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apartment_room'), table_name='apartment')
    op.create_index('ix_apartment_room', 'apartment', ['room'], unique=False)
    # ### end Alembic commands ###
