"""add field verify_code and verify

Revision ID: 9ae29a3b2d33
Revises: 00929f208960
Create Date: 2023-09-29 20:34:34.524949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae29a3b2d33'
down_revision: Union[str, None] = '00929f208960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isVerify', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('verification_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['verification_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'isVerify')
    # ### end Alembic commands ###
