"""add field apartment_type

Revision ID: b890fa5f01e0
Revises: b1371afb21d2
Create Date: 2023-11-23 22:02:39.005338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b890fa5f01e0'
down_revision: Union[str, None] = 'b1371afb21d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('apartment_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'apartment_type')
    # ### end Alembic commands ###
