"""add desc for amenity

Revision ID: be3d7a62a6d5
Revises: 82700bb19e8b
Create Date: 2023-10-30 20:46:44.187052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3d7a62a6d5'
down_revision: Union[str, None] = '82700bb19e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenity', sa.Column('desc', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_amenity_desc'), 'amenity', ['desc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amenity_desc'), table_name='amenity')
    op.drop_column('amenity', 'desc')
    # ### end Alembic commands ###
