"""add user_id foreignkey in apartment

Revision ID: cf606252e069
Revises: 14b9cde99ca5
Create Date: 2023-11-29 16:43:13.051801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf606252e069'
down_revision: Union[str, None] = '14b9cde99ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'apartment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartment', type_='foreignkey')
    op.drop_column('apartment', 'user_id')
    # ### end Alembic commands ###
