"""update avatar user and add more cols

Revision ID: e595b8efd939
Revises: 743c878e00d0
Create Date: 2023-11-12 13:15:09.104736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e595b8efd939'
down_revision: Union[str, None] = '743c878e00d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apartment_image_apartment_id_fkey', 'apartment_image', type_='foreignkey')
    op.create_foreign_key(None, 'apartment_image', 'apartment', ['apartment_id'], ['id'], ondelete='CASCADE')
    op.add_column('contract', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.add_column('contract', sa.Column('num_of_people', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('system_role', sa.String(length=52), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'system_role')
    op.drop_column('contract', 'num_of_people')
    op.drop_column('contract', 'total_amount')
    op.drop_constraint(None, 'apartment_image', type_='foreignkey')
    op.create_foreign_key('apartment_image_apartment_id_fkey', 'apartment_image', 'apartment', ['apartment_id'], ['id'])
    # ### end Alembic commands ###
