"""add more field rating in apartment comment

Revision ID: eb4cfd92c13f
Revises: 95507121d9bf
Create Date: 2023-11-13 22:40:30.070172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4cfd92c13f'
down_revision: Union[str, None] = '95507121d9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_comment', sa.Column('rate_location', sa.Integer(), nullable=False))
    op.add_column('apartment_comment', sa.Column('rate_amenities', sa.Integer(), nullable=False))
    op.add_column('apartment_comment', sa.Column('rate_interior', sa.Integer(), nullable=False))
    op.add_column('apartment_comment', sa.Column('rate_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment_comment', 'rate_price')
    op.drop_column('apartment_comment', 'rate_interior')
    op.drop_column('apartment_comment', 'rate_amenities')
    op.drop_column('apartment_comment', 'rate_location')
    # ### end Alembic commands ###
